class Strings {
  static const String APP_NAME = "Burçlar";

  static const List<String> HOROSCOPE_NAMES = [
    "Koc",
    "Boga",
    "Ikizler",
    "Yengec",
    "Aslan",
    "Basak",
    "Terazi",
    "Akrep",
    "Yay",
    "Oglak",
    "Kova",
    "Balik"
  ];

  static const List<String> HOROSCOPE_DATES = [
    "21 Mart - 20 Nisan",
    "21 Nisan - 21 Mayıs",
    "22 Mayıs - 22 Haziran",
    "23 Haziran - 22 Temmuz",
    "23 Temmuz - 22 Agustos",
    "23 Agustos - 22 Eylül",
    "23 Eylül - 22 Ekim",
    "23 Ekim - 21 Kasım",
    "22 Kasım - 21 Aralık",
    "22 Aralık - 21 Ocak",
    "22 Ocak - 19 Subat",
    "20 Subat - 20 Mart"
  ];

  static const List<String> HOROSCOPES_DETAIL = [
    "Genel Özellikler\n\n"
        "Kişisel Özellikleriniz:\n"
        "\tKoç, Burçlar kuşağının ilk burcudur. Hareketli ve enerjik oluşları ile tanınırlar. Ben egoları çok fazla gelişmiştir. BEN, onların aynası olmuştur adeta. Bu burçta doğanlar çok pratiktirler. Olaylar karşısında coşkularını gizleyemezler. Yaşam yolunda canlılıklarını ve atılganlıklarını yitirmeden heyecanla ilerlerler. Merak ettikleri konularda olabildiğince yaratıcılardır. Amaçları doğrultusunda ilerlerken, kendilerini eylemleri ile kanıtlamak isterler. Eğer Koç'lar girişimde bulunacakları zaman izleyecekleri rotayı ayrıntıları ile planlarsa, enerjik yapılarının da yardımı ile daha da üretken olabilirler. Bencilliklerinden kaynaklanan sabırsızlıkları ve söz dinlemez yaratılışları yüzünden zaman zaman güç durumlara düştükleri de olur. Böyle anlarda başladıkları işlerini sonuçlandırmadan bırakırlar. Konuşmaları abartılıdır, bazen gerçekleri değiştirerek anlatırlar. Kavrama yetenekleri fazla olan Koç'lar yaşam sahnesinin başrolünde olmayı tercih ederler. Aşırı kıskanç ve bağımsızlıklarına düşkün olurlar.\n\n"
        "Yönetici yıldızınız: Mars\n\n"
        "Grubunuz: Ateş\n\n"
        "Uğurlu gününüz: Salı\n\n"
        "Uğurlu sayınız: 8\n\n"
        "Uğurlu renginiz: Ateş kırmızısı\n\n"
        "Uğurlu taşlarınız: Opal, elmas, safir\n\n"
        "Uğurlu çicekleriniz: Lale, papatya\n\n"
        "Uğurlu kokularınız: Manolya, lavanta, ıtır\n\n"
        "Olumlu özelliğiniz: Cesaret\n\n"
        "Olumsuz özelliğiniz: Acelecilik\n\n"
        "Anlaştığınız burçlar:Aslan, Yay\n\n"
        "Anlaşamadığınız burçlar: Yengeç, Terazi, Oğlak\n\n"
        "Başarılı olacağınız meslekler: Politikacılık, yöneticilik, işletmecilik, mühendislik, ressamlık, müzisyenlik, oyunculuk\n\n"
        "Burcunuzdan olan ünlüler: Fatih Sultan Mehmet,Sakıp Sabancı, Descartes, Charlie Chaplin, Vincent Van Gogh, Zeki Alasya\n\n",
    "Genel Özellikler\n\n"
        "Kişisel Özellikleriniz:\n"
        "\tBoğa'lar hedefleri doğrultusunda ilerlerken, tüm dikkatlerini toplayabilme yeteneklerinin yanında maddecilikleri ile tanınırlar. SAHİP olma onların yaşam gerçekleridir. Bireysel ilişkiler konusunda son derece güvenilir olan Boğa'lar, insanlara yardım etmekten hoşlanırlar. Yaşamları boyunca güven ararlar ve bu yüzden kendilerini riske atmazlar. Amaçladıkları işler konusunda gösterdikleri sabır, bazen diğer kişileri çatlatacak boyutlarda olabilir. Bütün bunlara rağmen çevresi tarafından aranılan, sıcakkanlı insanlardır. Sürekli somut konularla uğraşmayı severler, doğada bulunan olaylardan örneklemelerle işlerini başarılı bir şekilde yürütürler. Bu yüzden ruhsal olarak da doyumlu kişilerdir. Olayları organize ederlerken rahatlıklarını gözetirler ve kendilerinin zevklerine uygun olmasına önem verirler. Yaşamdaki isteklerini elde ettikleri zaman, hiçbir koşul onları başka yönlere çekemez. Parayı rahata ulaşmak için bir araç olarak görürler. Mal ve mülk edinme konusunda beceriklidirler. Finans ve yatırım konuları ilgilerini çeker.\n\n"
        "Yönetici yıldızınız: Venüs\n\n"
        "Grubunuz: Toprak\n\n"
        "Uğurlu gününüz: Cuma\n\n"
        "Uğurlu sayınız: 6\n\n"
        "Uğurlu renginiz: Pastel Mavi, Lila\n\n"
        "Uğurlu taşlarınız: Krizokol, Turkuaz, Safir\n\n"
        "Uğurlu çicekleriniz: Kırmızı gül, pembe karanfil ve şebboy\n\n"
        "Uğurlu kokularınız: Karanfil, elma çiçeği\n\n"
        "Olumlu özelliğiniz: Güvenilirlik\n\n"
        "Olumsuz özelliğiniz: İnatçılık\n\n"
        "Anlaştığınız burçlar: Yengeç, Balık\n\n"
        "Anlaşamadığınız burçlar: Kova, Aslan, Akrep\n\n"
        "Başarılı olacağınız meslekler: Askerlik, doktorluk, mimarlık, mühendislik, bankacılık\n\n"
        "Burcunuzdan olan ünlüler:  Nükhet Duru, Öztürk Serengil, Salvadore Dali, Karl Marks, Lenin, Sigmund Freud, Shakespare\n\n",
    "Genel Özellikler\n\n"
        "Kişisel Özellikleri\n"
        "\tİkizler burcu insanları hızlı düşüncelerine uygun çabuk hareket ederler. Ayni anda birkaç işi birden yapabilirler. Onların adapte olamayacakları iş yoktur. Bu yüzden değişik karakterli olmaları ile tanınırlar. Bu yapılarını her zaman görebilmek mümkündür. Son derece neşeli ve mutlu oldukları bir anda, aniden mutsuz olabilirler. Çevreleri tarafından sürekli yanlış anlaşılabilirler. Herhangi bir konuda bilgileri az bile olsa, bunu çok iyi gizlemeyi başarırlar. Aksine; kulaktan dolma duydukları bilgileri öyle ustaca anlatırlar ki, dinleyenler onları o işin uzmanı sanırlar. Pratik zekalarıyla, çekici ve akıllıdırlar. Bu nedenle onları tanımlayan sözcük 'Düşünüyorum' dur. Fakat, bu düşünceleri hep yeni arayışlara doğru yönelmiştir. Bu yüzden uzun soluklu çalışmalar onları yorar. Kendilerini iyi eğitmiş ikizler hoş ve zariflikleri ile yaşamı zevkli kılarlarken, eğitimsiz olanlar da yaşamı o kadar çekilmez hale getirirler. Kendi paralarına karşı tutumlu davranmalarına karşın, başkalarının paralarını kolayca harcayabilirler.\n\n"
        "Yönetici yıldızınız: Merkür\n\n"
        "Grubunuz: Hava\n\n"
        "Uğurlu gününüz: Çarşamba\n\n"
        "Uğurlu sayınız: 5\n\n"
        "Uğurlu renginiz: Sarı\n\n"
        "Uğurlu taşlarınız: Kuvars, Akik, Turkuaz\n\n"
        "Uğurlu çicekleriniz: Çiğdem, mimoza\n\n"
        "Uğurlu kokularınız: Gardenya, sümbül, yasemin\n\n"
        "Olumlu özelliğiniz: Konuşkan olmak\n\n"
        "Olumsuz özelliğiniz: Kararsızlık\n\n"
        "Anlaştığınız burçlar: Terazi, Kova, Aslan\n\n"
        "Anlaşamadığınız burçlar: Başak, Yay\n\n"
        "Başarılı olacağınız meslekler: Yazarlık, bankacılık, avukatlık, gazetecilik, edebiyatçı\n\n"
        "Burcunuzdan olan ünlüler: Adile Naşit, Bülent Ecevit, John F. Kennedy, John Wayne, Schumann\n\n",
    "Genel Özellikler\n\n"
        "Kişisel Özellikleriniz:\n"
        "\tYaşamlarındaki her konuda aşırı bir şekilde hassas, alıngan ve kuruntulu olan Yengeç'leri tanımlayan sözcük 'Hissederim' dir. Sorumluluk duyguları çok gelişmiştir. Her işte olağanüstü olan ayrıntıcılıkları, işlerinde mükemmeliyetçiliği getirir. Ayni sorumlulukları karşılarındakilerden de beklerler. Yengeç'ler duygusallıkları ve duyarlılıkları ile tanınırlar. Çevresindeki her insandan da ayni hassasiyeti bekledikleri için, kolay geçinilir tipler değildir. İyi günlerinde neşeli, iyi kalpli, yardımsever, düşünceli ve anlayışlıdırlar. Fakat herhangi belirgin bir neden olmadan somurtkan ve alıngan olabilirler. Yakınlarını ve arkadaşlarını çok sevmelerine karşın, bunu pek belli etmezler. Kendilerini herhangi bir şekilde inciten kişileri zor bağışlarlar ve yapılan hareketi asla unutmazlar. Yengeç'ler müziğe ve dinsel konulara karşı ilgilidirler. Sabırlı olan Yengeç'ler tartışmalardan kesinlikle hoşlanmazlar. Duygularını sessiz bir şekilde saklarlar.\n\n"
        "Yönetici yıldızınız: Ay\n\n"
        "Grubunuz: Su\n\n"
        "Uğurlu gününüz: Pazartesi\n\n"
        "Uğurlu sayınız: 2\n\n"
        "Uğurlu renginiz: Beyaz\n\n"
        "Uğurlu taşlarınız: Ametist, Pembe kuvars\n\n"
        "Uğurlu çicekleriniz: Nilüfer, beyaz gül, zambak\n\n"
        "Uğurlu kokularınız: Misk, müge, leylak\n\n"
        "Olumlu özelliğiniz: Sabırlı olmak\n\n"
        "Olumsuz özelliğiniz: Dikkatsizlik\n\n"
        "Anlaştığınız burçlar: Boğa, Balık\n\n"
        "Anlaşamadığınız burçlar: Koç, Aslan, Kova\n\n"
        "Başarılı olacağınız meslekler: Eczacılık, turizm, pilotluk, kimyagerlik\n\n"
        "Burcunuzdan olan ünlüler: Sezen Aksu, Türkan Şoray, Louis Armstrong, Tom Cruise, Giorgio Armani, Lady Diana\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tAslan kraldır, önderdir. Başkalarının yaşantılarını da onlar adına düzenlemek isterler. Her şeye karışırlar, kibirlidirler. Bu nedenle onları tanımlayan sözcük 'Yönetirim' dir. Yaşam sahnesinde her zaman parlayarak, odak noktası olmak isterler. Organizasyon güçleri çok fazladır. İsteklerini başkalarına kabul ettirmek, onlar için yaşamlarının 'olmazsa olmaz' şartıdır. İyi zamanlarında etkileyici, güler yüzlü, başkalarına yardım etmeyi seven ve bunu kendine görev sayan Aslan'lar sevimli ve iyimser kişilerdir. Ona karşı hatalı davransanız bile, size olgun bir şekilde tepki verir. Fakat; Sabrı taştıktan sonra, dürüst ve mert, gerektiğinde sert bir şekilde tavır gösterir. Zor günlerinde şansları onlara her zaman yardım eder. Yönetici gezegenleri Güneş onları en karanlık günlerinde aydınlığa çıkarır. Eğitimsiz ve gelişmemiş Aslan tipleri çekilmez olurlar. Her konuda sahip olduklarından daha fazlası varmış gibi davranırlar.\n\n"
        "Yönetici yıldızınız: Güneş\n\n"
        "Grubunuz: Ateş\n\n"
        "Uğurlu gününüz: Pazartesi\n\n"
        "Uğurlu sayınız: 1\n\n"
        "Uğurlu renginiz: Sarı\n\n"
        "Uğurlu taşlarınız: Sardoniks, Peridot, Krizolit\n\n"
        "Uğurlu çicekleriniz: Kırmızı gül, sarı krizantem ve orkide\n\n"
        "Uğurlu kokularınız: Misk, portakal çiçeği ve gül\n\n"
        "Olumlu özelliğiniz: Cömertlik\n\n"
        "Olumsuz özelliğiniz: Kendini beğenmişlik\n\n"
        "Anlaştığınız burçlar: Koç, Yay\n\n"
        "Anlaşamadığınız burçlar: Boğa, Akrep, Kova\n\n"
        "Başarılı olacağınız meslekler: Askerlik, doktorluk, yöneticilik\n\n"
        "Burcunuzdan olan ünlüler: Uğur Mumcu, Gönül Yazar, Neil Armstrong, Benito Mussolini, Fidel Castro, Henry Ford, Madonna\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tYönetici gezegeninizden dolayı hep bilgiyi ararlar. Zekalarını kendilerine yardımcı olan bir hizmetçi gibi görürler. Bu nedenle Başak burcunu tanımlayan sözcük 'İncelerim “ dir. Başak'lar çalışkan ve pratik insanlar olup, yaşamlarındaki en önemli konu İş' tir. Güvendikleri kişilere yardım etmeyi sevmelerine rağmen, inanmadıkları ve tembel olduklarını bildikleri kişilere karşı soğuk davranırlar. Yaşamları boyunca dinlenmeden çalışırlar. Onların dinlenme biçimi bile başkalarına yorucu gelebilir. Başak'ların yaşamda ayrıntılar arasında boğulma riskleri hep vardır. Böyle anlarda bile, kendi yöntemleri ile yaptıkları işlerde gelişigüzel şeyler bulunabileceğini kabul etmezler. Başaklar, genellikle kendilerini hiç kimseye kullandırtmazlar, sınırlarını belirleyerek 'hayır' demesini bilirler. Tutumlulukları bazen pintilik derecesindedir. İçli-dışlı olmayı sevmedikleri için, soğuk ve mesafeli bir görünüşleri vardır.\n\n"
        "Yönetici yıldızınız: Merkür\n\n"
        "Grubunuz: Toprak\n\n"
        "Uğurlu gününüz: Çarşamba\n\n"
        "Uğurlu sayınız: 5\n\n"
        "Uğurlu renginiz: Kobalt mavisi\n\n"
        "Uğurlu taşlarınız: Ametist, Akik, Yeşim Taşı, Zümrüt\n\n"
        "Uğurlu çicekleriniz: Açelya, sarı menekşe, lavanta çiçeği\n\n"
        "Uğurlu kokularınız: Leylak, limon ve sardunya\n\n"
        "Olumlu özelliğiniz: Titizlik\n\n"
        "Olumsuz özelliğiniz: Çekingenlik\n\n"
        "Anlaştığınız burçlar: Boğa, Oğlak\n\n"
        "Anlaşamadığınız burçlar: İkizler, Yay, Balık\n\n"
        "Başarılı olacağınız meslekler: Edebiyat alanı, yazarlık, eczacılık, muhasebecilik , araştırmacılık\n\n"
        "Burcunuzdan olan ünlüler: Büyük İskender, Uğur Dündar, Sophia Loren, Michael Jackson, Vitali Hakko, Richard Gere, Sean Connery\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tKararsızlıkları ile ünlü cazibe sembolü karşınızda duruyor. Nedenini bilmediğiniz bir çekim gücü etkisi altına girdiğinizi fark ettiğinizde iş işten çoktan geçmiş olacaktır. Onların büyülü bir havası vardır. Ritmik hareketleri ile dans eder gibi bir yaşam sürer. Onun yanında kızgınlıklarınız yok olur. En sinirli anınızda bile sizi regüle etme yeteneğine sahiptir. Üstelik, tartışmayı sevmesine rağmen; bu kadar ustalıkla konulara hakim olup, sonrada sesini hiç yükseltmeden zaferini ilen eden çok az kişi vardır. Bir Terazi bunu başarır. Sizin kılıç salladığınız ortamlarda, o; gülücüklerini, zarafetini ve öpücüklerini gönderecektir. Kafasında müthiş bir denge vardır. Onun ne düşündüğünü bilemezsiniz. Uyumlu ve sevecen yapısının altında gizli bir güç vardır. Bulunduğu ortamları çok çabuk inceler ve gizli detayların nerede saklı olduğunu bulmaya çalışır. Konuya hakim olmak için deliler gibi çalışmak ve kendini harap etmek yerine, keskin görüşlerini ve doğru mantığını kullanacağı ortamları seçer. Başarılı olmak için imkansızlığı değil, kendini yüceltecek elle tutulur konular üzerinde uyumlu bir sessizlikle çalışır. Yaptığı işlerin doğruluğuna inandığı halde, onay beklemekten de kendini alamaz. Onu tenkit etme gibi bir şansınız asla olamaz. Böyle bir şeye kalkıştığınız taktirde; size tüm zarafetiyle gülümseyecek, önerilerinizi can kulağıyla dinleyecek ve sonunda kibarca teşekkür ederek sizden uzaklaşacaktır. Fakat bir daha asla sizin fikrinizi sormayacaktır. Gülümseyen çehresinin altında müthiş bir ego gizlidir, aşk ve sanat onun yaşam öğeleridir. Dünyada her şeyden vazgeçebilir, fakat kişiliğini besleyen ve duygusallığını yansıtan soyut kavramlarından vazgeçemez. Akıl, mantık, aşk işte karşınızda her şeyiyle özel bir kişi duruyor. Onun terazilerinin kefesinde yer almak istiyorsanız, belli standart ölçülerin çok üstünde olmanız gerekir. Kolay bir insan olmadığını şimdiden hatırlatırız.\n\n"
        "Yönetici yıldızınız: Venüs\n\n"
        "Grubunuz: Hava\n\n"
        "Uğurlu gününüz: Cuma\n\n"
        "Uğurlu sayınız: 6\n\n"
        "Uğurlu renginiz: Turkuaz ve mat renkler\n\n"
        "Uğurlu taşlarınız: Lapis Lazuli, Mercan, Opal\n\n"
        "Uğurlu çicekleriniz: Pembe krizantem, pembe gül\n\n"
        "Uğurlu kokularınız: Gardenya, yasemin ve orkide\n\n"
        "Olumlu özelliğiniz: Zariflik\n\n"
        "Olumsuz özelliğiniz: Gösteriş meraklısı olmak\n\n"
        "Anlaştığınız burçlar: İkizler, Kova\n\n"
        "Anlaşamadığınız burçlar: Koç, Yengeç, Oğlak\n\n"
        "Başarılı olacağınız meslekler: Müzisyenlik, ressamlık, mimarlık, bankacılık, politikacılık, hukukçuluk, heykeltraşlık\n\n"
        "Burcunuzdan olan ünlüler: Cem Özer, Hülya Avşar, Cervantes, Oscar Wilde, Pavorotti, Turgut Özal, Pavorotti, Jimmy Carter\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tAkrepler kadar yaşamda tutkuyla yaşayan az insan vardır. Bu nedenle onları simgeleyen sözcük 'Arzuluyorum' dur. Hiçbir şeyi yarım bırakmazlar. Akreplerin güçleri gözlerinden okunur. Mimiklerini kontrol altında tutsalar bile, bakışları ile sevgilerini ya da nefretlerini aktarabilirler. Duygularına kapılırlarsa, tehlikeli olabilirler. Akrep'ler ukala ve kendini beğenmiş insanları sevmezler, onları aşağılayarak hadlerini bildirirler. Kendi bildiklerini okuyarak, uzlaşmaya yanaşmazlar. Aşırı bir şekilde kuşkuculardır, kolay inanmazlar ama inandıkları bir konuyu da sonuna kadar inatla savunurlar. Çalışmalarında sabır ve özenle çalışırlarken, gösterişten uzak bir şekilde işlerini yaparlar. Kendilerini yetiştirmemiş Akrep'ler, yaşamın basitliklerine yatkınlıkları ile kendi kendilerinin yok oluşlarına neden olurlar. Cinsellik yaşamlarında önemli bir yer tutar. Ölümü yeni bir başlangıç olarak kabul ettiklerinden, ölümden korkmazlar..\n\n"
        "Yönetici yıldızınız: Mars-Plüton\n\n"
        "Grubunuz: Su\n\n"
        "Uğurlu gününüz: Salı\n\n"
        "Uğurlu sayınız: 9\n\n"
        "Uğurlu renginiz: Kırmızı ve siyah\n\n"
        "Uğurlu taşlarınız: Akuamarin, Lapis Lazuli, Opal\n\n"
        "Uğurlu çiçekleriniz: Kırmızı karanfil, hanımeli, ateş çiçeği\n\n"
        "Uğurlu kokularınız: Misk, manolya\n\n"
        "Olumlu özelliğiniz: Kararlılık\n\n"
        "Olumsuz özelliğiniz: Merhametsizlik ve ihmarkarlık\n\n"
        "Anlaştığınız burçlar: Yengeç, Balık\n\n"
        "Anlaşamadığınız burçlar: Boğa, Aslan, Kova\n\n"
        "Başarılı olacağınız meslekler: Yöneticilik, mühendislik, komutanlık, yazarlık, müzisyenlik, gazetecilik\n\n"
        "Burcunuzdan olan ünlüler: Süleyman Demirel, Maradona, Pablo Picasso, Prenses Charles, Indra Gandhi, Alfred Nobel\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tKavrama yetenekleri gelişmiş olduğundan becerikliliklerinin de katkısı ile ele aldıkları her işte, özellikle ciddi işlerde ve felsefe konularında başarılı olurlar. Bu nedenle Yay Burcunu tanımlayan sözcük 'Görüyorum' dur. Yay burcu insanları içtenlikleri ve iyimser yaşam görüşleri ile tanınırlar. Gençliklerinde dikkatsiz, heyecanlı ve geleneklere aykırı davranışlar içinde olsalar da, geçmiş yanılgılarından en çok ders alan kişiler bu burçtan çıkar. Özgürlüklerine aşırı düşkün, patavatsızlık derecesinde pratik insanlardır. Yay'ların yaşam çerçeveleri herhangi bir şekilde kısıtlandığı zaman, içsel bir biçimde alt üst olurlar. Akılsızca risklere atılırlar. Yayların hayatı yeniliklere olan merakları ile karakterize edilebilir. Bilmedikleri şeyleri araştırıp, keşfetmeyi severler. Yaylar çok yönlü ve ayni anda ilgilenebilecekleri birkaç konu olduğunda mutlu olan kişilerdir. Kendilerini yorgun hissediyorlarsa, o konudan sıkılmış demektir.\n\n"
        "Yönetici yıldızınız: Jüpiter\n\n"
        "Grubunuz: Ateş\n\n"
        "Uğurlu gününüz: Perşembe\n\n"
        "Uğurlu sayınız: 3\n\n"
        "Uğurlu renginiz: Mor ve koyu mavi\n\n"
        "Uğurlu taşlarınız: Obsidyen, Krizolit, Topaz\n\n"
        "Uğurlu çicekleriniz: Leylak, mor menekşe\n\n"
        "Uğurlu kokularınız: Nergis, menekşe, zambak\n\n"
        "Olumlu özelliğiniz: Girişimcilik\n\n"
        "Olumsuz özelliğiniz: Başkalarını küçümsemek\n\n"
        "Anlaştığınız burçlar: Koç, Aslan\n\n"
        "Anlaşamadığınız burçlar: İkizler, Başak, Balık\n\n"
        "Başarılı olacağınız meslekler: Politikacılık, hukukçu, araştırmacılık, bankacılık, öğretmenlik\n\n"
        "Burcunuzdan olan ünlüler:  Mehmet Ali Birand, Zeki Müren, Walt Disney, Winston Churchill, Ludwig van Beethoven, Mark Twain\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tGeleceği ayrıntılı biçimde planlamaya çalışan Oğlak'lar bu özellikleri nedeniyle sık sık kuruntulara kapılarak, depresyona girerler. İşleri ile aşırı meşgul olduklarından, insanlarla zor ilişki kurarlar. Fakat, hiçbir zaman kendilerini yalnız hissetmezler. Bu nedenle onları tanımlayan sözcük 'Kullanırım' dır. Oğlaklar ciddilikleri, tutuculukları ve güçlü iradeleri ile tanımlanırlar. Çalışkanlıkları ile kolaylıkla başkalarının saygısını kazanırlar. Gerçek bir Oğlak'ın iki temel özelliği vardır. Güvenilirlik ve dürüstlük. Çok gelişmiş bir görev duyguları vardır. Bazen başkalarının başarısızlıklarını abartırlar. Oğlaklar arkadaşları ile ilgili çok iyi sırdaş olurlar, para konusunda dikkatli olmalarına rağmen, eli açık insanlardır. Geleneklere bağlı kişiler olduklarından, duygusal özgürlüğü anlamakta güçlük çekerler. Bu nedenle kendilerinden yaşça küçük kişilerle bazen sürtüşmeleri olur. Sürekli somut konularla uğraşmayı severler, doğada bulunan olaylardan örneklemelerle işlerini başarılı bir şekilde yürütürler. Bu yüzden ruhsal olarak da doyumlu kişilerdir. Olayları organize ederlerken rahatlıklarını gözetirler ve kendilerinin zevklerine uygun olmasına önem verirler. Bu özellikleri evlerine de yansır."
        "Yönetici yıldızınız: Satürn\n\n"
        "Grubunuz: Toprak\n\n"
        "Uğurlu gününüz: Cumartesi\n\n"
        "Uğurlu sayınız: 8\n\n"
        "Uğurlu renginiz: Koyu kahverengi ve gri\n\n"
        "Uğurlu taşlarınız: Kuvars, Yakut, Kehribar\n\n"
        "Uğurlu çicekleriniz: Siyah gül, kadife çiçeği, kamelya\n\n"
        "Uğurlu kokularınız: Kamelya, cam, fulya\n\n"
        "Olumlu özelliğiniz: Kararlılık ve sağlam adımlar atmak\n\n"
        "Olumsuz özelliğiniz: Aşırı meraklı olmak\n\n"
        "Anlaştığınız burçlar: Boğa, Başak\n\n"
        "Anlaşamadığınız burçlar: Koç, Yengeç, Terazi\n\n"
        "Başarılı olacağınız meslekler: Güzellik uzmanlığı, mimarlık, madencilik, doktorluk, kuyumculuk\n\n"
        "Burcunuzdan olan ünlüler:  Filiz Akın, Semra Özal, Benjamin Franklin, Elvis Presley, Isaac Newton\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tHayal güçleri sınırsız olmakla birlikte, düşünceleri bulundukları anın ötesinde, akılcı ve sezgiseldir. Kova 'lar dik kafalıdırlar. Kendilerini dinleyenlerin ne demek istediklerini anlamadıklarını sanırlar. Kovaları tanımlayan sözcük 'Biliyorum' dur. Kova burcu insanları sevecen tavırları ile tanınırlar. Bu kişiler bencil değildirler. Irk, cinsiyet ve sosyal durumuna bakmaksızın, herkesin ayni olanaklara sahip olmasını isterler. Modern görünüşlerine karşın, inatçı ve sabit fikirli olurlar. Onlara yaklaşmak çok zordur, çünkü ne kadar dostça davranırlarsa davransınlar, arada her zaman bir mesafe bırakırlar. Kişisel özgürlükleri onlar için o denli önemlidir ki, bu yüzden en yakın ilişkilerini kesip atabileceği gibi, yine özgürlükleri adına her türlü özveride bulunurlar. Bu yüzden Kovalara aile yaşamı biraz zor gelir. Çoğu zaman yeni bir şeyler keşfetmek için uğraşıda bulunurlar. Belli ilkeleri sonuna dek savunmaları onları hiç rahatsız etmez.\n\n"
        "Yönetici yıldızınız: Uranüs\n\n"
        "Grubunuz: Hava\n\n"
        "Uğurlu gününüz: Pazar\n\n"
        "Uğurlu sayınız: 4\n\n"
        "Uğurlu renginiz: Lacivert\n\n"
        "Uğurlu taşlarınız: Ametist, Gümüş, Grena\n\n"
        "Uğurlu çicekleriniz: Zerren, menekşe, kartopu, kır çiçekleri ve kuşburnu\n\n"
        "Uğurlu kokularınız: Sümbül, yasemin, menekşe\n\n"
        "Olumlu özelliğiniz: İradeli olmak\n\n"
        "Olumsuz özelliğiniz: İhmarkarlık\n\n"
        "Anlaştığınız burçlar: İkizler, Terazi\n\n"
        "Anlaşamadığınız burçlar: Boğa, Aslan, Akrep\n\n"
        "Başarılı olacağınız meslekler: Yazarlık, editörlük, gazetecilik, sanatçılık, organizatörlük, muhasebecilik\n\n"
        "Burcunuzdan olan ünlüler: Ajda Pekkan, Mozart, Ronald Reagan, Schubert, Abraham Lincoln, Kim Novak\n\n",
    "Genel Özellikler\n\n"
        "Kişisel özellikleriniz:\n"
        "\tSabır, eli açıklık ve duyarlılık bu burçta doğan kişilerin en önemli nitelikleridir. Büyük bir inandırma yetenekleri vardır. Dürüst, vicdan sahibi, sadık ve uysaldırlar. Her çevreye kolayca uyabilirler. Genellikle hayal dünyasında yaşarlar. Yaşam görüşleri ciddi fakat gerçekçi değildirler. Balık burcu, diğer burçlar arasında dış etkenlerden en çok etkilenen kişilerdir. Düş dünyasında, öylesine mutludur ki, bazen onun aptal olduğunu bile düşünebilirsiniz. Ama, zannettiğinizden daha akıllı ve kurnazdır. Sinirli yapısını gizli bir sakinlikle örterken, herkesin seçtiği özel bir kişi olmanın hayallerini kurarlar. Yaşam onun için ürkütücü ve korkunçtur..Balık burcu insanını dışarıdan gözlemleyenler; duygusal yapısının bir aşk acısına dayanamayacağını zannederler ve kötü haberi hemen vermek istemezler. Aslında, kırılgan görüntüsünün altında güçlü bir kişilik yatar. Göz yaşlarını kısa sürede kurutur ve mendillerini bir kenara atarak, yeni bir yaşamın içinde kendini bulur. Onları teselli edecek o kadar kişi bulunur ki; yeni bir aşk acısı kapısını çalıncaya kadar, hayatını istediği gibi yaşar. Duygusal kırıklıklar pes etmelerine yetmez ve bir sürü yarım kalmış aşkıyla birlikte bir dolu anlatılacak anılarıyla yaşamını tamamlar.\n\n"
        "Yönetici yıldızınız: Neptün\n\n"
        "Grubunuz: Su\n\n"
        "Uğurlu gününüz: Perşembe\n\n"
        "Uğurlu sayınız: 7\n\n"
        "Uğurlu renginiz: Turkuaz ve yeşil\n\n"
        "Uğurlu taşlarınız: Turkuaz, Ametist, Pembe Kuvars\n\n"
        "Uğurlu çicekleriniz: İnci çiçeği, zambak\n\n"
        "Uğurlu kokularınız: Kiraz çiçeği, zambak, limon çiçeği\n\n"
        "Olumlu özelliğiniz: Şefkatli ve merhametli olmak\n\n"
        "Olumsuz özelliğiniz: Kendinizi küçümsemek\n\n"
        "Anlaştığınız burçlar: Yengeç, Akrep\n\n"
        "Anlaşamadığınız burçlar: İkizler, Başak, Yay\n\n"
        "Başarılı olacağınız meslekler: Öğretmenlik, müzisyenlik, yazarlık, doktorluk\n\n"
        "Burcunuzdan olan ünlüler: Beyazıt Öztürk, Hidayet Türkoğlu, Beren Saat, Yuri Gagarin, Albert Einstein, Gorbachev\n\n",
  ];
}
